### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by supersh86** [slhck/ffmpeg-bitrate-stats#5]
Hi, after installation, I get an error.

`Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg_bitrate_stats", line 7, in <module>
    from ffmpeg_bitrate_stats.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/ffmpeg_bitrate_stats/__main__.py", line 22
    print(msg, file=sys.stderr)
                   ^
SyntaxError: invalid syntax`

**Comment by slhck** [comment]
This tool is not written for Python 2.7. Please upgrade to Python 3.6 or higher.

**Comment by supersh86** [comment]
`pip install ffmpeg_bitrate_stats` ???

**Comment by supersh86** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg_bitrate_stats", line 7, in <module>
    from ffmpeg_bitrate_stats.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/ffmpeg_bitrate_stats/__main__.py", line 103
    print_stderr(f"Calculating frame size from {self.input_file}")
                                                                ^
SyntaxError: invalid syntax
