### ISSUE TITLE
SyntaxError: invalid syntax #2

### ISSUE THREAD

**Issue by supersh86** [slhck/ffmpeg-bitrate-stats#6]
Hi, after installation, I get an error.

`Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg_bitrate_stats", line 7, in <module>
    from ffmpeg_bitrate_stats.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/ffmpeg_bitrate_stats/__main__.py", line 103
    print_stderr(f"Calculating frame size from {self.input_file}")
                                                                ^
SyntaxError: invalid syntax`

**Comment by slhck** [comment]
As mentioned, you need at least Python 3.6. Your error indicates you're using 3.5.

**Comment by supersh86** [comment]
ok!
`Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg_bitrate_stats", line 5, in <module>
    from ffmpeg_bitrate_stats.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/ffmpeg_bitrate_stats/__main__.py", line 15, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'`

Should I create a new issuses?
