### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by TannerQuigley** [slhck/ffmpeg-bitrate-stats#9]
This is the error I get when I run using either the pip or repo. Same error on both. I'm using python 3.6. I cloned today

Traceback (most recent call last):
  File "/home/tquigley/.conda/envs/scrape/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tquigley/.conda/envs/scrape/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tquigley/ffmpeg-bitrate-stats/ffmpeg_bitrate_stats/__main__.py", line 385, in <module>
    main()
  File "/home/tquigley/ffmpeg-bitrate-stats/ffmpeg_bitrate_stats/__main__.py", line 380, in main
    br.calculate_statistics()
  File "/home/tquigley/ffmpeg-bitrate-stats/ffmpeg_bitrate_stats/__main__.py", line 92, in calculate_statistics
    self._calculate_duration()
  File "/home/tquigley/ffmpeg-bitrate-stats/ffmpeg_bitrate_stats/__main__.py", line 183, in _calculate_duration
    self.duration = round(sum(f["duration"] for f in self.frames), 2)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by slhck** [comment]
Can you please supply a video file with which I can reproduce this error?

**Comment by slhck** [comment]
(I think I know what's going on but I cannot reproduce it with any video I have here.)
